include classpath("application.conf")

aws {
    accountId = "000011112222"
}

queues {
    local_product_inited {
        defaultVisibilityTimeout = 10 seconds
        delay = 5 seconds
        receiveMessageWait = 0 seconds
    }
}
