name: Build and Push

on:
  push:
    tags:
      - '*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.22.1

    - name: Build Go binary for Linux
      run: GOOS=linux GOARCH=amd64 go build -o ./bin/your-service-name ./cmd/main.go

    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        # create your personal access token in GitHub and add it to the repository secrets
        password: ${{ secrets.GHCR_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./build/Dockerfile
        push: true
        tags: ghcr.io/gonozov0/your-service-name:${{ github.ref_name }}
