name: Lint and Test

on:
  push:
    branches: [ main ]
    tags-ignore: ['*']
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Install dependencies
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/segmentio/golines@latest
          go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest                                                                                            260ms  Fri Jun 21 15:17:48 2024
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Lint code
        run: |
          unformatted=$(go fmt ./...)
          if [ -n "$unformatted" ]; then 
            echo "These files are not formatted with 'go fmt': $unformatted"
            exit 1
          fi
          unformatted=$(find . -name '*.go' ! -path "./generated/*" -exec goimports -local go-echo-ddd-template/ -l {} +)
          if [ -n "$unformatted" ]; then
            echo "These files are not formatted with 'goimports': $unformatted"
            exit 1
          fi
          unformatted=$(find . -name '*.go' ! -path "./generated/*" -exec golines -w {} -m 120 \;)
          if [ -n "$unformatted" ]; then
            echo "These files are not formatted with 'golines': $unformatted"
            exit 1
          fi
          golangci-lint run ./...

      - name: Check go generate
        run: ./check-go-generate.sh
        shell: bash

  test:
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.1

      - name: Run tests
        run: go test -coverpkg=./... -count=1 -coverprofile=coverage.out ./...
        env:
          REDIS_ADDRESS: localhost:6379

      - name: Upload coverage to GitHub Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out
